export const qualifications = [
  "Bachelor's degree",
  "Master's degree",
  "Doctorate degree",
  "Professional Certificate",
  "Diploma",
  "Associate degree",
  "Secondary education",
  "High school",
  "Undergraduate",
  "Graduate",
  "Other",
]


export const skills = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "UI/UX Designer",
  "Mobile Developer",
  "DevOps",
  "Database Administrator",
  "System Administrator",
  "QA Engineer",
  "Architect",
  "Software Engineer",
  "Project Manager",
  "Technical Writer",
  "Content Writer",
  "Marketing Specialist",
  "SEO Specialist",
  "Social Media Specialist",
  "Community Manager",
  "Business Analyst",
  "Product Manager",
  "Sales Associate",
  "Customer Support Specialist",
  "IT Manager",
  "HR Specialist",
  "Accountant",
  "Finance Specialist",
  "Legal Specialist",
  "Human Resources Specialist",
  "Recruiter",
  "Consultant",
  "Other",
];